version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_flask
      MYSQL_USER: d_flask
      MYSQL_PASSWORD: 123123
    volumes:
      - C:\Users\user\OneDrive\Desktop\docker\01_bmi\bmi_schema.sql:/docker-entrypoint-initdb.d/bmi_schema.sql

  flask:
    # # 本地端建立，需先拉python映像
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # 別的主機進行docker-compose pull會拉此映像
    image: happy0106/flask_bmi_image:latest #必須寫push到docker hub上的完整名稱
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8188:80"
    volumes:
      - C:\Program Files\nginx-1.25.4\conf\nginx.conf:/etc/nginx/nginx.conf  # 此處確保路徑正確
    depends_on:
      - flask